# Generated by Django 2.1.2 on 2018-10-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
