# Generated by Django 2.1.2 on 2018-10-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20181026_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='модерация'),
        ),
        migrations.AlterField(
            model_name='news',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_min',
            field=models.TextField(max_length=300, verbose_name='Текст мин'),
        ),
    ]
